volt_id = "eb982eb8-8638-4e19-b6fe-978d3bc41449"

[settings]
server = "ampere"
wrap = "cargo build --release"

cache = ["target"]
hash = ["crates/volt", "crates/volt-server", "Cargo.toml", "Cargo.lock"]
